default_model: deepseek-chat
models:
  deepseek-chat:
    provider: deepseek
    request:
      temperature: 0.1
      max_tokens: 8192
      timeout: 60
    max_context_tokens: 128000
  gpt-5:
    provider: openai
    request:
      temperature: 0.1
      max_tokens: 128000
      timeout: 60
    max_context_tokens: 400000
  gpt-4o:
    provider: openai
    request:
      temperature: 0.1
      max_tokens: 16384
      timeout: 60
    max_context_tokens: 128000
  gpt-4o-mini:
    provider: openai
    request:
      temperature: 0.1
      max_tokens: 16384
      timeout: 60
    max_context_tokens: 128000
  gpt-3.5-turbo:
    provider: openai
    request:
      temperature: 0.1
      max_tokens: 4096
      timeout: 60
    max_context_tokens: 16358
api_keys:
  deepseek: ''
  openai: ''
permissions:
  allow:
    - FileListTool
    - FileReadTool
    - GlobTool
    - GrepTool
    - TodoWriteTool
    - TaskTool
  deny: []
  ask: []
